name: bobs_coffee
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  mobile_scanner: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/loyalty_default.png
  uses-material-design: true
  generate: true

l10n:
    arb-dir: lib/l10n
    template-arb-file: intl_en.arb
    output-localization-file: app_localizations.dart
    output-class: AppLocalizations
    supported-locales:
      - en
      - ru
      - ro

uses-material-design: true

assets:
  - assets/images/logo.png
  - assets/images/loyalty_default.png
